import './assets/css/button.css';

export default {
    title: 'Example/Button'
  };
  export const Default = () => '<button class="btn">Default Button</button>'
  export const Primary = () => '<button class="btn primary-btn">Primary Button</button>'
  export const Success = () => '<button class="btn success-btn">Success Button</button>'
  export const Danger = () => '<button class="btn danger-btn">Danger Button</button>'
  export const Warning = () => '<button class="btn warning-btn">Warning Button</button>'
  export const Info = () => '<button class="btn info-btn">Info Button</button>'
  export const Light = () => '<button class="btn light-btn">Light Button</button>'
  export const Dark = () => '<button class="btn dark-btn">Dark Button</button>'
  export const Link = () => '<button class="btn link-btn">Link Button</button>'
  export const Outline_Primary = () => '<button class="btn outline primary-btn">Primary Button</button>'
  export const Outline_Success = () => '<button class="btn outline success-btn">Success Button</button>'
  export const Outline_Danger = () => '<button class="btn outline danger-btn">Danger Button</button>'
  export const Outline_Warning = () => '<button class="btn outline warning-btn">Warning Button</button>'
  export const Outline_Info = () => '<button class="btn outline info-btn">Info Button</button>'
  export const Outline_Light = () => '<button class="btn outline light-btn">Light Button</button>'
  export const Outline_Dark = () => '<button class="btn outline dark-btn">Dark Button</button>'
  export const Swipe = () => '<button class="btn swipe-btn">Swipe Button</button>'
  export const Bubble = () => '<button class="btn bubble-btn">Bubble Button</button>'
  export const Border_01 = () => '<button class="btn border-btn-01"><svg><rect x="0" y="0" fill="none" width="100%" height="100%"><p>Border Button 01</p></rect></svg></button>'
  export const Border_02 = () => '<button class="btn border-btn-02">Border Button 02</button>'
  export const Border_03 = () => '<button class="btn border-btn-03">Border Button 03</button>'
  export const Shadow = () => '<button class="btn shadow-btn">Shadow Button</button>'
  export const Shining = () => '<button class="btn shining-btn">Shining Button</button>'
  export const Glow = () => '<button class="btn glow-btn">Glow Button</button>'
  export const Flip = () => '<button class="btn flip-btn" data-back="Flip Back" data-front="Flip Front"></button>'
  export const Linebox = () => '<button class="btn linebox-btn">Linebox Button</button>'
  export const Icon = () => '<button class="btn icon-btn"><span class="circle"><span class="icon arrow"></span></span><span class="btn-text">Icon Button</span></button>'